# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-11-27 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='year_in_school',
            field=models.CharField(choices=[(b'SC', b'Seleccione una categoria'), (b'DTI', b'Deportes tropicales de invierno'), (b'ER', b'Entretenimiento para robots'), (b'OPA', b'Orden Publico Alterado'), (b'Ch', b'Chibchombia'), (b'NO', b'Negocios ociosos')], default=b'SC', max_length=2),
        ),
    ]
