# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-11-27 21:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0002_noticia_year_in_school'),
    ]

    operations = [
        migrations.RenameField(
            model_name='noticia',
            old_name='year_in_school',
            new_name='categoria',
        ),
    ]
