# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-11-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0003_auto_20171127_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[(b'SC', b'Seleccione una categoria'), (b'DTI', b'Deportes tropicales de invierno'), (b'ER', b'Entretenimiento para robots'), (b'OPA', b'Orden Publico Alterado'), (b'Ch', b'Chibchombia'), (b'NO', b'Negocios ociosos')], default=b'SC', max_length=3),
        ),
    ]
