# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-18 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0004_auto_20171127_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(choices=[('SC', 'Seleccione una categoria'), ('DTI', 'Deportes tropicales de invierno'), ('ER', 'Entretenimiento para robots'), ('OPA', 'Orden Publico Alterado'), ('Ch', 'Chibchombia'), ('NO', 'Negocios ociosos')], default='SC', max_length=3),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='imagen',
            field=models.ImageField(upload_to='imagenes'),
        ),
    ]
