# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-12-20 04:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticias', '0006_noticia_destacado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='destacado',
            field=models.NullBooleanField(),
        ),
    ]
